### ISSUE TITLE
how do is use this?

### ISSUE THREAD

**Issue by Dr-Bob-isTheBestDoctor** [Milk-Cool/flippulator#2]
i am not very new to linux but i don't know how to comile or build this project and some commands like make or npm start will give lots of errors.

**Comment by Milk-Cool** [comment]
hello. what errors exactly? and did you specify the path to the app you want to build?

**Comment by Dr-Bob-isTheBestDoctor** [comment]
well i want to try to use ble spam from the xtreme firmware from the flipper zero and when i give npm start i don't know if i have to give more arguments it gives this error


> flippulator@0.1.0 start
> node index.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:util'
Require stack:
- /home/bobtiemessen/Desktop/flippulator-main/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/bobtiemessen/Desktop/flippulator-main/index.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/bobtiemessen/Desktop/flippulator-main/index.js' ]
}



hope this helps a bit

**Comment by Milk-Cool** [comment]
firstly, you'll need to run `npm i` before building anything to install the nodejs dependencies. secondly, you might be using an outdated version of nodejs since it doesn't have `util`. and finally, bluetooth is not supported yet, so you'll have to wait

**Comment by Dr-Bob-isTheBestDoctor** [comment]
ok thanks also npm is the latest version(8.5.1~ds-1)
